### ISSUE TITLE
fix broken firefox config

### ISSUE THREAD

**Issue by MystixCode** [MystixCode/postinstall_debian11#1]
The firefox config doesnt work on debian 11 anymore.
Find the issue and fix it ;)

**Comment by Ronqn** [comment]
Thanks for the infos! I just made the changes and I'm trying the script to see if everything works correctly.

**Comment by MystixCode** [comment]
And if you try to get 4 pull requests for hacktoberfest u might want to fork the project, do the changes there and then create a pull request
